### ISSUE TITLE
Can we get this to work with the Sony A7iii?

### ISSUE THREAD

**Issue by rojasjason** [ma1co/OpenMemories-Framework#23]
Hi, 

I was just wondering if there is any development towards making this work with the recently released sony a7iii?

Thank you.

**Comment by 0000x1** [comment]
I'm thinking to buy a a7m3,and want to know that too.

**Comment by jonasjuffinger** [comment]
This is sadly not possible and will never be. Sony dropped the app support for all new cameras because there firmware is not based on Android anymore.

**Comment by rojasjason** [comment]
Not with that attitude it isn't.

**Comment by ma1co** [comment]
Correct. Afaik, Sony has removed the android subsystem.
