### ISSUE TITLE
How to Bulb shooting?

### ISSUE THREAD

**Issue by gtvwp** [ma1co/OpenMemories-Framework#24]
I set 'Manual-ExposureF2.8 ISO200',
set shutter speed by 'camera.adjustShutterSpeed()',
check shutter speed by 'camera.setShutterSpeedChangeListener  onShutterSpeedChange()'.
It seems succeeded to set bulb speed.
and then call 'camera.takePicture(null, null, null)'.

But shutter speed is force to 30sec, not bulb.
How can I shoot bulb?

**Comment by gtvwp** [comment]
I succeeded to shoot bulb mode.
probrem is caused by 'paramsModifier.setDriveMode("burst");'...

**Comment by rohhn** [comment]
Hi, 

It may be too late now, can you post some code for doing this?
