### ISSUE TITLE
Can't install Openmemories Tweak on SONY RX10 (I)

### ISSUE THREAD

**Issue by Hira108** [ma1co/OpenMemories-Framework#36]
Hello,

I'm trying to install the Tweak on the first version of the SONY RX10 (firmware 2.0). The app sees the camera, but I get the MTP error 0x2006.

The camera is new and has no apps installed - I don't know if this is a problem. I actually can't find any PlayMemories folder in the camera menu. Is it possible to install the tweak?

Thanks!

**Comment by ma1co** [comment]
Please use the "Tweaks" tab in pmca-gui.
