### ISSUE TITLE
A99 II supprot

### ISSUE THREAD

**Issue by frankywong** [ma1co/OpenMemories-Framework#8]
Any plan to if/when A99 II (ILCA-99M2) will be supported?

**Comment by ma1co** [comment]
I have a dump of the A99M2 firmware. Sadly, there is no Android subsystem, so there is no way to run apps :(

However, if you're just interested in tweaking settings, there is a new experimental way for that using the firmware update functionality. Read more about it [here](https://github.com/ma1co/Sony-PMCA-RE#tweaking-camera-settings). Keep in mind that you are probably the first person to test this on an A99M2, so your mileage may vary. If you run into any problems, please let us know!
